### ISSUE TITLE
Support to 5.0

### ISSUE THREAD

**Issue by arthurbailao** [hired/stretchy#40]
Any plans to support breaking changes of Elasticsearch 5.0?

**Comment by agius** [comment]
Yes, we will need to in order to keep our stack up to date. There are [quite a few breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/breaking-changes-5.0.html), so we should probably get started soon 😸 Thanks for the poke!

**Comment by agius** [comment]
Update: see #41

**Comment by agius** [comment]
@arthurbailao Released [0.7.0](https://rubygems.org/gems/stretchy/versions/0.7.0). 

I should probably just bump the breaking changes to major versions now; I may never consider this gem "better" than beta status 😹
